---
- name: Start app
  hosts: all
  become: true

  tasks:
    - name: Create container from image
      docker_container:
        name: reddit
        image: "mikelog/otus-reddit:1.0"
        network_mode: host
